name: js定时签到hifini

on:
  schedule:
    # 每天 北京时间 01:15
    - cron: '15 17 * * *'
  # 可选：手动触发按钮
  workflow_dispatch:

jobs:
  Hifiti-Sign:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '16'
    - name: 音乐磁场签到
      run: node hifini_sign_20250821.js "jxmh1991@163.com" "jin19910414"
