name: Run JAR on Schedule

on:
  schedule:
    # 每天 UTC 时间 17:15 运行（北京时间 01:15）
    - cron: '15 17 * * *'
    
    # 每天 UTC 时间 05:15 运行（北京时间 13:15）
    - cron: '15 5 * * *'
  # 可选：手动触发按钮
  workflow_dispatch:

jobs:
  run-jar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Hifiti Sign
        run: java -jar HifitiSign-1.0.20250730.jar
